
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   labels:
#     app: myapp
# spec:
#   type: NodePort
#   ports:
#   - port: 3306
#     nodePort: 3306
#     protocol: TCP
#     name: http
#   selector:
#     app: myapp
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-deployment
#   labels:
#     app: myapp
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: myapp
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - name: mysql
#         image: services/mysql
#         ports:
#         - containerPort: 3306
#         imagePullPolicy: Never

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 3306
  selector:
    app: myapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: services/mysql
          name: mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim