apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadminapp
spec:
  ports:
  - port: 80
  selector:
    app: phpmyadminapp
    tier: admin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadminapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadminapp
  template:
    metadata:
      labels:
        app: phpmyadminapp
    spec:
      containers:
        - name: phpmyadmin
          image: services/phpmyadmintest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 5000
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
            - name: PMA_PASSWORD
              value: root
            - name: PMA_ABSOLUTE_URI
              value: /
            - name: MYSQL_ROOT_PASSWORD
              value: root